import 'package:flutter/material.dart';
import '../theme/app_colors.dart';

class TermsPage extends StatelessWidget {
  const TermsPage({super.key});

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    final bgColor = theme.scaffoldBackgroundColor;
    final textColor = theme.colorScheme.onSurface;
    final accentColor = theme.colorScheme.primary;

    return Scaffold(
      backgroundColor: bgColor,
      appBar: AppBar(
        title: Text(
          'Privacy Policy & Terms',
          style: TextStyle(
            fontFamily: 'Raleway',
            fontSize: 20,
            color: textColor,
            fontWeight: FontWeight.bold,
          ),
        ),
        backgroundColor: bgColor,
        iconTheme: IconThemeData(color: textColor),
        elevation: 0,
      ),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Terms and Conditions',
              style: TextStyle(
                fontFamily: 'Raleway',
                fontSize: 24,
                color: accentColor,
                fontWeight: FontWeight.bold,
              ),
            ),
            const SizedBox(height: 16),
            Text(
              'By using DermaLens, you agree to the following terms:\n\n'
              '1. AI-Generated Content\n'
              'The content, reports, and diagnoses provided by DermaLens are generated by Artificial Intelligence (AI). While our model is highly advanced, AI can make mistakes and is not infallible.\n\n'
              '2. Not Professional Medical Advice\n'
              'The information provided by DermaLens is for educational and informational purposes only and should not be considered a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider for any skin condition.\n\n'
              '3. Data Privacy\n'
              'We take your privacy seriously. Your uploaded images are processed securely and your data will not be sold to third parties.',
              style: TextStyle(
                fontFamily: 'Raleway',
                fontSize: 15,
                color: textColor.withOpacity(0.8),
                height: 1.5,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
