import 'package:flutter/material.dart';
import '../theme/app_colors.dart';

class TermsPage extends StatelessWidget {
  const TermsPage({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.surface,
      appBar: AppBar(
        title: const Text(
          'Privacy Policy & Terms',
          style: TextStyle(
            fontFamily: 'Raleway',
            fontSize: 20,
            color: AppColors.sand,
            fontWeight: FontWeight.bold,
          ),
        ),
        backgroundColor: AppColors.surface,
        iconTheme: const IconThemeData(color: AppColors.sand),
        elevation: 0,
      ),
      body: const SingleChildScrollView(
        padding: EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Text(
              'Terms and Conditions',
              style: TextStyle(
                fontFamily: 'Raleway',
                fontSize: 24,
                color: AppColors.warmGold,
                fontWeight: FontWeight.bold,
              ),
            ),
            SizedBox(height: 16),
            Text(
              'By using DermaLens, you agree to the following terms:\n\n'
              '1. AI-Generated Content\n'
              'The content, reports, and diagnoses provided by DermaLens are generated by Artificial Intelligence (AI). While our model is highly advanced, AI can make mistakes and is not infallible.\n\n'
              '2. Not Professional Medical Advice\n'
              'The information provided by DermaLens is for educational and informational purposes only and should not be considered a substitute for professional medical advice, diagnosis, or treatment. Always consult with a qualified healthcare provider for any skin condition.\n\n'
              '3. Data Privacy\n'
              'We take your privacy seriously. Your uploaded images are processed securely and your data will not be sold to third parties.',
              style: TextStyle(
                fontFamily: 'Raleway',
                fontSize: 15,
                color: AppColors.sand,
                height: 1.5,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
