services:
  backend:
    build:
      context: ./dermalens_backend
      dockerfile: Dockerfile
    container_name: dermalens_backend
    ports:
      - "8000:8000"
    volumes:
      - ./dermalens_backend:/app
    env_file:
      - ./dermalens_backend/.env
    environment:
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    container_name: dermalens_cache
    ports:
      - "6379:6379"
    restart: always
