import 'dart:typed_data';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:intl/intl.dart';
import 'scan_service.dart';

class PdfService {
  final ScanService _scanService = ScanService();

  Future<void> exportScanHistory() async {
    final pdf = pw.Document();
    final scans = await _scanService.getScanHistory();
    
    // Load font for professional look
    final font = await PdfGoogleFonts.ralewayRegular();
    final fontBold = await PdfGoogleFonts.ralewayBold();

    // Define Colors (Gold & White as requested)
    const goldColor = PdfColor.fromInt(0xFFC4956A);
    const whiteColor = PdfColors.white;
    const darkColor = PdfColor.fromInt(0xFF1A1714);

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          // 1. Header with Branding
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'DermaLens',
                    style: pw.TextStyle(
                      font: fontBold,
                      fontSize: 28,
                      color: goldColor,
                    ),
                  ),
                  pw.Text(
                    'Personal Clinical Report',
                    style: pw.TextStyle(
                      font: font,
                      fontSize: 14,
                      color: darkColor.flatten(),
                    ),
                  ),
                ],
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: [
                  pw.Text(
                    DateFormat('MMMM dd, yyyy').format(DateTime.now()),
                    style: pw.TextStyle(font: font, fontSize: 12),
                  ),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 20),
          pw.Divider(color: goldColor, thickness: 2),
          pw.SizedBox(height: 20),

          // 2. Summary Section
          pw.Container(
            padding: const pw.EdgeInsets.all(16),
            decoration: pw.BoxDecoration(
              color: goldColor,
              borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
            ),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.center, // Centered now
              children: [
                _buildSummaryStat('Total Scans Performed', scans.length.toString(), whiteColor, fontBold, font),
              ],
            ),
          ),
          pw.SizedBox(height: 32),

          // 3. Detailed Records Table
          pw.Text(
            'Diagnostic History Summary',
            style: pw.TextStyle(font: fontBold, fontSize: 18, color: darkColor),
          ),
          pw.SizedBox(height: 16),
          
          pw.Table(
            border: pw.TableBorder.all(color: goldColor, width: 0.5),
            columnWidths: {
              0: const pw.FlexColumnWidth(2),
              1: const pw.FlexColumnWidth(4),
              2: const pw.FlexColumnWidth(2),
            },
            children: [
              // Table Header
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: goldColor),
                children: [
                  _buildTableCell('Date', whiteColor, fontBold, isHeader: true),
                  _buildTableCell('Identified Condition', whiteColor, fontBold, isHeader: true),
                  _buildTableCell('Risk Level', whiteColor, fontBold, isHeader: true),
                ],
              ),
              // Table Rows
              ...scans.map((scan) {
                final date = scan["created_at"]?.toString().split('T')[0] ?? "N/A";

                return pw.TableRow(
                  children: [
                    _buildTableCell(date, darkColor, font),
                    _buildTableCell(scan["condition"] ?? "Unknown", darkColor, fontBold),
                    _buildTableCell(scan["severity"] ?? "Unknown", darkColor, font),
                  ],
                );
              }),
            ],
          ),


          pw.SizedBox(height: 40),
          
          // 4. Disclaimer
          pw.Divider(color: goldColor, thickness: 0.5),
          pw.SizedBox(height: 10),
          pw.Text(
            'DISCLAIMER: This report is generated by AI and is intended for informational purposes only. It does not constitute professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.',
            style: pw.TextStyle(font: font, fontSize: 8, color: PdfColors.grey700),
            textAlign: pw.TextAlign.center,
          ),
        ],
      ),
    );

    // Open the PDF viewer immediately (Allows viewing, saving, and printing)
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'DermaLens_Report_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
  }

  pw.Widget _buildSummaryStat(String label, String value, PdfColor color, pw.Font fontBold, pw.Font font) {
    return pw.Column(
      children: [
        pw.Text(label, style: pw.TextStyle(font: font, fontSize: 10, color: color)),
        pw.Text(value, style: pw.TextStyle(font: fontBold, fontSize: 20, color: color)),
      ],
    );
  }

  pw.Widget _buildTableCell(String text, PdfColor color, pw.Font font, {bool isHeader = false, double fontSize = 10}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(font: font, fontSize: fontSize, color: color),
      ),
    );
  }
}
